### ISSUE TITLE
Create an index.html page

### ISSUE THREAD

**Issue by simranquirky** [simranquirky/MULONE#7]
the index.html page will be the landing page of the webapp. it will contain a 'GET STARTED' button which will redirect to main.html page

**Comment by Radhey100** [comment]
What we have to write in index file

**Comment by simranquirky** [comment]
You need to create a simple web page with a button. The button will contain "Get started" option.

**Comment by Radhey100** [comment]
Ok I will add a also animation css if you like

**Comment by simranquirky** [comment]
Sure start  working on it. I am really surprised of the knowledge you possess. Eagerly waiting to see your work 😀

**Comment by Radhey100** [comment]
Haha, thanks!  I am from class 6 I was little bit confused when I make pull
request please accept this is my first contribution and I am agerly waiting
for my first star

**Comment by simranquirky** [comment]
Sure

**Comment by Radhey100** [comment]
Great, thanks!  I will makw the button then anyone click so I have to make
that also or only button

**Comment by Radhey100** [comment]
I have to study also so I can send at 7pm

**Comment by c0d3-br34k3r** [comment]
> the index.html page will be the landing page of the webapp. it will contain a 'GET STARTED' button which will redirect to main.html page

I would like to contribute for the repo. You can assign this project to me.

**Comment by simranquirky** [comment]
> > the index.html page will be the landing page of the webapp. it will contain a 'GET STARTED' button which will redirect to main.html page
> 
> I would like to contribute for the repo. You can assign this project to me.

Hey @TheInvincibleLearner you can work on issue #1 , radhey is new and young so issue #7 will be easy for him to do.

**Comment by c0d3-br34k3r** [comment]
> > > the index.html page will be the landing page of the webapp. it will contain a 'GET STARTED' button which will redirect to main.html page
> > 
> > 
> > I would like to contribute for the repo. You can assign this project to me.
> 
> Hey @TheInvincibleLearner you can work on issue #1 , radhey is new and young so issue #7 will be easy for him to do.

Sure Then you just assign the issue #1 to me. I would love to contribute.

**Comment by c0d3-br34k3r** [comment]
@simranquirky Is @Radhey100 doing this pull request ??? Else I would like to contribute to this issue as well if he is not adding any proper code.

**Comment by simranquirky** [comment]
@TheInvincibleLearner you can start working on this . I am assigning it to you.

**Comment by simranquirky** [comment]
@Radhey100 you know a lot about git and GitHub, and many more things. I appreciate that. But you are not yet ready to contribute to a project. Keep learning and try next time!

**Comment by c0d3-br34k3r** [comment]
Okay @simranquirky I would start the work soon and then submit for the pull request. Thanks for assigning it to me.

**Comment by c0d3-br34k3r** [comment]
@simranquirky I have done the creation of index.html page with some design and get started button. Renamed two css files - that were connected to main.html and index.html. Stay assured nothing got broken. Do have a look at the pull request and approve it if you like my work. Follow me if you like my work...:innocent: Also let me know if the design was okay or not.
